# Generated by Django 2.1.3 on 2018-11-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tane', '0003_auto_20181128_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('promotion', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tane.Promotion')),
            ],
        ),
    ]
